export const GET_HOME_DATA = "GET_HOME_DATA";
export const GET_FOOTER_DATA = "GET_FOOTER_DATA";
export const GET_COMPANY_PROFILE_DATA = "GET_COMPANY_PROFILE_DATA";
export const GET_INFRASTRUCTURE_DATA = "GET_INFRASTRUCTURE_DATA";
export const GET_MEDIA_DATA = "GET_MEDIA_DATA";
export const GET_COLLECTION_DATA = "GET_COLLECTION_DATA";
export const GET_EXPORT_DATA = "GET_EXPORT_DATA";
export const IS_FIRST_TIME = "IS_FIRST_TIME";
